---
title: "BARRY_1_230919_run"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r message=FALSE}

rm(list=ls())

library(RColorBrewer)
library(tidyverse)
library(ComplexHeatmap)
library(UpSetR)

```

# BARRY analysis

First attempt with aborted run. 

### Set dirs
```{r}

workingdir="~/Dropbox (The Francis Crick)/DP_cisReg/"
subworkinput="input_BARRY_1"

```


## Colors and shapes
Before more plotting, let's get some metadata organised

```{r }
sorted_gate <- c("pMN","DP","p3","DN")

shapes4_manual = c(18,15,16,17) # these are block
shapes5_manual = c(25,21,22,23,24) # these are filled
shapes4_fill_manual = c(23,21,22,24)
 

color_gates <- c("#e60000","#cd00cd","#0073e6","#696969")

# for Days
colors_greys <- c("#f6f6f6","#808080","#333333")


```

### import data

```{r  import-domain}

barry_data <- lapply(list.files(path=paste0(workingdir,subworkinput),pattern=".*.fastq.gz.txt", full.names=TRUE),function(x) {
  data <- read.csv(x,header=F,stringsAsFactors=F) %>% as.data.frame()
  data$sample <- gsub(paste0("/Users/delasj/Dropbox \\(The Francis Crick\\)/DP_cisReg/",subworkinput,"/"),"", x)
  data$sample <- gsub("_R1_001.fastq.gz.txt","",data$sample)
  #data <- data %>% column_to_rownames(sample)
  data
})

barry_results <- do.call(rbind,barry_data) %>% column_to_rownames("sample")

```


#### Convert any count > 0 to 1
Make binary matrix for quick comparisons

```{r}
# test1 <- barry_results
# test1 <- test1 %>% column_to_rownames("sample")
# test <- test1[1:3,5:15]

barry_binary <- as.matrix((barry_results>0)+0)

```

#### Some numbers

```{r, fig.width=8, fig.height=4}

barcodes_per_sample <- rowSums(barry_binary) %>% as.data.frame() %>%
  rownames_to_column("sampleid") %>%
  separate(sampleid, into = c("Day","Gate","Rep","discard"), sep = "_", remove = FALSE) 


ggplot(barcodes_per_sample, aes(x=Gate,y=get(names(barcodes_per_sample)[6]))) +
  geom_col(aes(fill=Rep), position=position_dodge()) +
  facet_grid(~ Day) +
  ylab("Unique barcodes per sample") +
  theme_bw()


```
```{r}

#test_binary <- barry_binary[1:4,5:35]

barcodes_shared <- colSums(barry_binary) %>% as.data.frame() %>% 
  rownames_to_column("BCid")

colnames(barcodes_shared) <- c("BCid","shared_samples")

ggplot(barcodes_shared, aes(x=reorder(BCid,-shared_samples), y=shared_samples)) +
  geom_col() + 
  theme_minimal() +
  theme(axis.text.x=element_blank(), axis.ticks.x=element_blank())

```

Product of matrix by t(matrix)


```{r}

i <- (colSums(barry_binary, na.rm=T) > 1) # T if colSum > 1, F otherwise
binary_keepshared <- barry_binary[, i] # all the non-zero columns

binary_keepshared_matrix2 <- binary_keepshared%*%t(binary_keepshared)

# binary_keep_samplename <- binary_keepshared_matrix2[,5:20] %>% as.data.frame() %>%
#   rownames_to_column("sampleid") %>%
#   separate(sampleid, into = c("Day","Gate","Rep","discard"), sep = "_", remove = FALSE)



```


```{r, fig.width=12, fig.height=10}

names(color_gates) <- sorted_gate


genecolData_first <- data.frame(Sample_ID = colnames(binary_keepshared_matrix2))

genecolData_first <- genecolData_first %>% 
  separate(Sample_ID,into=c("Day","Gate","Rep","discard"), sep="_", remove=FALSE) 

genecolData_first <- as.data.frame(unclass(genecolData_first))



phen_data <- genecolData_first %>%
  select(c("Sample_ID","Day","Gate","Rep")) %>%
  remove_rownames() %>%
  column_to_rownames("Sample_ID")
ann_color_JD <- list(Gate=color_gates, 
    Day = c(D4="#f6f6f6",D5="#cecece",D6="#808080",D7="#333333"),
  Rep = c(A="#ebeb77", B="#77b1eb"))


# Build the annotation for the complex heatmap
heatmap_ann_row <- rowAnnotation(df=phen_data, col=ann_color_JD)
heatmap_ann <- HeatmapAnnotation(df=phen_data, col=ann_color_JD, show_legend = FALSE)



# Annotated heatmap with selected colors
hm_colors = colorRampPalette(rev(brewer.pal(n = 11, name = "RdBu")))(100)


Heatmap(binary_keepshared_matrix2, name="Shared barcodes", col=hm_colors,
        cluster_columns = TRUE, cluster_rows = TRUE,
        #show_column_dend = FALSE,
        #row_dend_side = "right", column_dend_side = "bottom",
        # cluster methods for rows and columns
        clustering_distance_columns = function(x) as.dist(1 - cor(t(x))),
        clustering_method_columns = 'ward.D2',
        clustering_distance_rows = function(x) as.dist(1 - cor(t(x))),
        clustering_method_rows = 'ward.D2',
        column_dend_height = unit(2, "cm"), row_dend_width = unit(2, "cm"),
        row_names_gp = gpar(fontsize = 10),column_names_gp = gpar(fontsize = 10),
        left_annotation = heatmap_ann_row, top_annotation = heatmap_ann,
        column_title = "Shared number of barcodes")




```


## For now repeat this with separeted replicates

```{r}



binary_keep_repA <- binary_keepshared %>% as.data.frame() %>%
  rownames_to_column("sampleid") %>%
  separate(sampleid, into = c("Day","Gate","Rep","discard"), sep = "_", remove = FALSE) %>%
  filter(Rep=="A") %>%
  select(!c("Day","Gate","Rep","discard")) %>%
  column_to_rownames("sampleid") %>%
  as.matrix()

binary_keep_repB <- binary_keepshared %>% as.data.frame() %>%
  rownames_to_column("sampleid") %>%
  separate(sampleid, into = c("Day","Gate","Rep","discard"), sep = "_", remove = FALSE) %>%
  filter(Rep=="B") %>%
  select(!c("Day","Gate","Rep","discard")) %>%
  column_to_rownames("sampleid") %>%
  as.matrix()



binary_keepshared_matrixA <- binary_keep_repA%*%t(binary_keep_repA)
binary_keepshared_matrixB <- binary_keep_repB%*%t(binary_keep_repB)

```

```{r, fig.width=8, fig.height=7}

names(color_gates) <- sorted_gate


genecolData_first <- data.frame(Sample_ID = colnames(binary_keepshared_matrixA))

genecolData_first <- genecolData_first %>% 
  separate(Sample_ID,into=c("Day","Gate","Rep","discard"), sep="_", remove=FALSE) 

genecolData_first <- as.data.frame(unclass(genecolData_first))



phen_data <- genecolData_first %>%
  select(c("Sample_ID","Day","Gate","Rep")) %>%
  remove_rownames() %>%
  column_to_rownames("Sample_ID")
ann_color_JD <- list(Gate=color_gates,
    Day = c(D4="#f6f6f6",D5="#cecece",D6="#808080",D7="#333333"),
  Rep = c(A="#ebeb77", B="#77b1eb"))


# Build the annotation for the complex heatmap
heatmap_ann_row <- rowAnnotation(df=phen_data, col=ann_color_JD)
heatmap_ann <- HeatmapAnnotation(df=phen_data, col=ann_color_JD, show_legend = FALSE)



# Annotated heatmap with selected colors
hm_colors = colorRampPalette(rev(brewer.pal(n = 11, name = "RdBu")))(100)


Heatmap(binary_keepshared_matrixA, name="Shared barcodes", col=hm_colors,
        cluster_columns = TRUE, cluster_rows = TRUE,
        #show_column_dend = FALSE,
        #row_dend_side = "right", column_dend_side = "bottom",
        # cluster methods for rows and columns
        clustering_distance_columns = function(x) as.dist(1 - cor(t(x))),
        clustering_method_columns = 'ward.D2',
        clustering_distance_rows = function(x) as.dist(1 - cor(t(x))),
        clustering_method_rows = 'ward.D2',
        column_dend_height = unit(2, "cm"), row_dend_width = unit(2, "cm"),
        row_names_gp = gpar(fontsize = 10),column_names_gp = gpar(fontsize = 10),
        left_annotation = heatmap_ann_row, top_annotation = heatmap_ann,
        column_title = "Shared number of barcodes")




```



```{r, fig.width=8, fig.height=7}

names(color_gates) <- sorted_gate



genecolData_first <- data.frame(Sample_ID = colnames(binary_keepshared_matrixB))

genecolData_first <- genecolData_first %>% 
  separate(Sample_ID,into=c("Day","Gate","Rep","discard"), sep="_", remove=FALSE) 

genecolData_first <- as.data.frame(unclass(genecolData_first))



phen_data <- genecolData_first %>%
  select(c("Sample_ID","Day","Gate","Rep")) %>%
  remove_rownames() %>%
  column_to_rownames("Sample_ID")
ann_color_JD <- list(Gate=color_gates, 
    Day = c(D4="#f6f6f6",D5="#cecece",D6="#808080",D7="#333333"),
  Rep = c(A="#ebeb77", B="#77b1eb"))


# Build the annotation for the complex heatmap
heatmap_ann_row <- rowAnnotation(df=phen_data, col=ann_color_JD)
heatmap_ann <- HeatmapAnnotation(df=phen_data, col=ann_color_JD, show_legend = FALSE)



# Annotated heatmap with selected colors
hm_colors = colorRampPalette(rev(brewer.pal(n = 11, name = "RdBu")))(100)


Heatmap(binary_keepshared_matrixB, name="Shared barcodes", col=hm_colors,
        cluster_columns = TRUE, cluster_rows = TRUE,
        #show_column_dend = FALSE,
        #row_dend_side = "right", column_dend_side = "bottom",
        # cluster methods for rows and columns
        clustering_distance_columns = function(x) as.dist(1 - cor(t(x))),
        clustering_method_columns = 'ward.D2',
        clustering_distance_rows = function(x) as.dist(1 - cor(t(x))),
        clustering_method_rows = 'ward.D2',
        column_dend_height = unit(2, "cm"), row_dend_width = unit(2, "cm"),
        row_names_gp = gpar(fontsize = 10),column_names_gp = gpar(fontsize = 10),
        left_annotation = heatmap_ann_row, top_annotation = heatmap_ann,
        column_title = "Shared number of barcodes")




```

### just to try
remove barcodes shared across many populations


```{r}

i <- (colSums(barry_binary, na.rm=T) > 1 & colSums(barry_binary, na.rm=T) < 6 ) # T if colSum > 1, F otherwise
binary_keepshared <- barry_binary[, i] # all the non-zero columns

binary_keepshared_matrix2 <- binary_keepshared%*%t(binary_keepshared)

```


```{r, fig.width=12, fig.height=10}

names(color_gates) <- sorted_gate


genecolData_first <- data.frame(Sample_ID = colnames(binary_keepshared_matrix2))

genecolData_first <- genecolData_first %>% 
  separate(Sample_ID,into=c("Day","Gate","Rep","discard"), sep="_", remove=FALSE) 

genecolData_first <- as.data.frame(unclass(genecolData_first))



phen_data <- genecolData_first %>%
  select(c("Sample_ID","Day","Gate","Rep")) %>%
  remove_rownames() %>%
  column_to_rownames("Sample_ID")
ann_color_JD <- list(Gate=color_gates, 
    Day = c(D4="#f6f6f6",D5="#cecece",D6="#808080",D7="#333333"),
  Rep = c(A="#ebeb77", B="#77b1eb"))


# Build the annotation for the complex heatmap
heatmap_ann_row <- rowAnnotation(df=phen_data, col=ann_color_JD)
heatmap_ann <- HeatmapAnnotation(df=phen_data, col=ann_color_JD, show_legend = FALSE)



# Annotated heatmap with selected colors
hm_colors = colorRampPalette(rev(brewer.pal(n = 11, name = "RdBu")))(100)


Heatmap(binary_keepshared_matrix2, name="Shared barcodes", col=hm_colors,
        cluster_columns = TRUE, cluster_rows = TRUE,
        #show_column_dend = FALSE,
        #row_dend_side = "right", column_dend_side = "bottom",
        # cluster methods for rows and columns
        clustering_distance_columns = function(x) as.dist(1 - cor(t(x))),
        clustering_method_columns = 'ward.D2',
        clustering_distance_rows = function(x) as.dist(1 - cor(t(x))),
        clustering_method_rows = 'ward.D2',
        column_dend_height = unit(2, "cm"), row_dend_width = unit(2, "cm"),
        row_names_gp = gpar(fontsize = 10),column_names_gp = gpar(fontsize = 10),
        left_annotation = heatmap_ann_row, top_annotation = heatmap_ann,
        column_title = "Shared number of barcodes")




```



```{r}
sessionInfo()
```
